### PR TITLE
Feature 2 commit 1

### PR DESCRIPTION
**Pull request by klktest**
Feature 2 commit 1

### CODE REVIEW

**Comment by klkreddy123** [comment]
Please check and merge the changes.

**Comment by klktest** [comment]
> Please check and merge the changes.

checked.

**Comment by klkreddy123** [comment]
> > Please check and merge the changes.
> 
> checked.

Add Forgot password feature 2

**Comment by klktest** [comment]
> > > Please check and merge the changes.
> > 
> > 
> > checked.
> 
> Add Forgot password feature 2

Added now

**Review by klkreddy123 — APPROVED** [review]
Approved.

**Pull request merged**
